import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/ui/SideNabar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${
          geistMono.variable
        }  h-screen w-full bg-white text-black flex antialiased ${
          process.env.NODE_ENV === "development" ? "debug-screens" : ""
        } `}
        cz-shortcut-listen="true"
        data-new-gr-c-s-check-loaded="14.1240.0"
        data-gr-ext-installed=""
      >
        {/* sidebar */}
        <SideNavbar />
        {/* main page */}
        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  );
}
